# Generated by Django 2.2 on 2021-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=8, verbose_name='carName')),
            ],
            options={
                'verbose_name': '车',
                'verbose_name_plural': '车',
                'db_table': 'car',
                'ordering': ['-id', 'car_name'],
            },
        ),
    ]
