# Generated by Django 2.2 on 2021-07-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0002_auto_20210704_1802'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
    ]
