# Generated by Django 2.2 on 2021-07-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0003_auto_20210704_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-id', 'car_name'], 'verbose_name': '车', 'verbose_name_plural': '车'},
        ),
    ]
