# Generated by Django 2.2 on 2021-11-29 14:58

from django.db import migrations, models
import practice.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20211129_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[practice.models.is_even_numbers])),
            ],
        ),
    ]
