# Generated by Django 2.2 on 2021-06-30 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type_name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na_name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pe_name', models.CharField(max_length=8)),
                ('pn', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=8)),
                ('cat_age', models.IntegerField(max_length=8)),
                ('ct', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Cat_type')),
            ],
        ),
    ]
