# Generated by Django 2.2 on 2021-06-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cat_cat_type_nationality_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_age',
            field=models.IntegerField(),
        ),
    ]
